// Generated by Wrangler on Fri Apr 19 2024 20:24:54 GMT-0300 (Argentina Standard Time)
// by running `wrangler types`

interface Env {
	PINATA_JWT: string;
	GATEWAY_URL: string;
	ENVIRONMENT: string;
	ANIMATRONIK_SEPOLIA_ADDRESS: string;
}
