/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  OwnableAbi,
  OwnableAbiInterface,
} from "../../../../../@openzeppelin/contracts/access/Ownable.sol/OwnableAbi";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class OwnableAbi__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableAbiInterface {
    return new Interface(_abi) as OwnableAbiInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): OwnableAbi {
    return new Contract(address, _abi, runner) as unknown as OwnableAbi;
  }
}
