/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ERC165Abi,
  ERC165AbiInterface,
} from "../../../../../../@openzeppelin/contracts/utils/introspection/ERC165.sol/ERC165Abi";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ERC165Abi__factory {
  static readonly abi = _abi;
  static createInterface(): ERC165AbiInterface {
    return new Interface(_abi) as ERC165AbiInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ERC165Abi {
    return new Contract(address, _abi, runner) as unknown as ERC165Abi;
  }
}
